### PR TITLE
Update start.sh to fix container

### PR DESCRIPTION
**Pull request by fraxker**
Recently, the container broke with an error message `/start.sh: line 5: /usr/bin/nordVpn.sh: No such file or directory`. This is potentially due to something upstream changing that I cannot fully determine. The `nordVpn.sh` file has been replaced with a `nordVpn` executable. The PR modifies the start.sh to use this new file.

### CODE REVIEW

**Comment by fraxker** [comment]
So what I originally thought was the new executable was not. It seems they have gotten rid of the script all together bringing greater issues in

**Comment by twitchax** [comment]
But this is still broken, right?

I can investigate.

**Comment by fraxker** [comment]
yes, this is broken but what I originally purpose does not actually fix it. I think this would do better as an issue.

**Comment by twitchax** [comment]
Ok, sounds good.

**Comment by twitchax** [comment]
@fraxker, fixed.  You have to use the `NordLynx` technology, but that's not a big deal because it is better anyway. :)

**Pull request closed without merging**
